### ISSUE TITLE
中文版链接 404

### ISSUE THREAD

**Issue by stfenjobs** [ochococo/Design-Patterns-In-Swift#108]
https://github.com/ochococo/Design-Patterns-In-Swift/blob/master/source-cn/contents.md

进去点击 会404

谢谢

**Comment by ochococo** [comment]
@Binlogo 👁️ 🙏

**Comment by Binlogo** [comment]
> https://github.com/ochococo/Design-Patterns-In-Swift/blob/master/source-cn/contents.md
> 
> 进去点击 会404
> 
> 谢谢

@stfenjobs 这不是在 GitHub 上直接浏览的链接哈，是用来生成 Playground 的，建议下载 playground 查看。

@ochococo This is not a cn-special issue or not a issue, the links works in the generated playground.

> https://github.com/ochococo/Design-Patterns-In-Swift/blob/master/source/contents.md

**Comment by stfenjobs** [comment]
谢谢
