### ISSUE TITLE
Improve readability in `./source/behavioral/chain_of_responsibility.swift`

### ISSUE THREAD

**Issue by VladimirCreator** [ochococo/Design-Patterns-In-Swift#120]
`./source/behavioral/chain_of_responsibility.swift` has an opportunity to improve readability.

Consider this snippet from the file:

```swift
if let next = self.next {
    return next.withdraw(amount: amount)
}
```

That could be rewritten as:

```swift
if let next {
    return next.withdraw(amount: amount)
}
```

Though, it requires newer version of the Swift programming language.

**Comment by VladimirCreator** [comment]
I'll make a pull request if you ask :)

**Comment by ochococo** [comment]
Awesome, thank you!
