### ISSUE TITLE
Singleton pattern might need a bit more to have it right..

### ISSUE THREAD

**Issue by naoufalmed** [ochococo/Design-Patterns-In-Swift#39]
To ensure that one and ONLY one instance of a class is created, there should be a bit more than just having a public shared instance. One have to ensure that nobody else can create another instance by making the initializer private. So, the example might be extended as follows:

```swift
class DeathStarSuperlaser {
    static let sharedInstance = DeathStarSuperlaser()

    private init(){
     // Do something ...
   }
}
```

> NOTE: In the playground the `private` scope might not be respected, since I could create instances of my singleton class even if the initializer was private, but in the "real" code I get the error "`'DeathStarSuperlaser' cannot be constructed because it has no accessible initializers`", when I try to crate an instance of my singleton by calling the initializer like this: `let anotherLaser = DeathStarSuperlaser()`

**Comment by ochococo** [comment]
Excellent point. I will fix that. Thank you!

**Comment by ochococo** [comment]
https://github.com/ochococo/Design-Patterns-In-Swift/compare/bugfix/singleton_private_init?expand=1

**Comment by ochococo** [comment]
https://github.com/ochococo/Design-Patterns-In-Swift/pull/40
