### ISSUE TITLE
To use multi paradigm

### ISSUE THREAD

**Issue by carlosypunto** [ochococo/Design-Patterns-In-Swift#53]
Maybe will be good to improve the examples with multi paradigm in mind. Please take a look at more simple Swift 2 Multi-paradigm Decorator Pattern https://gist.github.com/carlosypunto/a179a9203b60c7b1c19357af717d0f54
Suggestions are welcome. Take the code if you want

For example in your Decorator code initialisers of Milk or WhipCoffee are no necesary

**Comment by ochococo** [comment]
@carlosypunto So your example (code formatting is burning my eyes btw) just used `.reduce` ... anybody can do that with current implementation.
