### ISSUE TITLE
UML diagrams

### ISSUE THREAD

**Issue by voloshynslavik** [ochococo/Design-Patterns-In-Swift#65]
Hi,
Thanks for a great work and excellent samples. If you can add UML diagrams to every pattern it will be nice.

**Comment by ochococo** [comment]
@YaroslavVoloshyn Thank you! Great idea for contribution, would you be able to help?

**Comment by toolshc** [comment]
For example, for Factory Method the example is Currency Factory

I think this is the diagram for the implementation

![](https://github.com/adagio/swiftFactoryMethodDP/raw/master/Diagrams/Currency-Factory.png)

**Comment by adagio** [comment]
for Adapter example, about OldDeathStar, this could be the diagram

![](https://github.com/adagio/swiftAdapterDP/raw/master/Diagrams/OldDeathStarAdapter.png)

**Comment by evgeniyd** [comment]
I highly appreciate the idea. Would be exelent to see the contibutions!

**Comment by haithngn** [comment]
could we add a new project on Draw.io to this idea ?

**Comment by ochococo** [comment]
Yeah, let’s do that
