### ISSUE TITLE
Factory design pattern implementation 

### ISSUE THREAD

**Issue by dddppp** [ochococo/Design-Patterns-In-Swift#66]
Is it possible to add an example of the **Factory design pattern** in **Swift**?

Here is an implementation example in **Java**:
https://www.tutorialspoint.com/design_pattern/factory_pattern.htm

Here is the difference between Java interfaces and Swift protocols:
http://stackoverflow.com/questions/30859334/compare-protocol-in-swift-vs-interface-in-java

Thanks!

**Comment by Pratik-Somaiya** [comment]
This looks interesting to include.
