### ISSUE TITLE
Separate repo with descriptions in Chinese 中文

### ISSUE THREAD

**Issue by ochococo** [ochococo/Design-Patterns-In-Swift#85]
(planned just after https://github.com/ochococo/Design-Patterns-In-Swift/tree/swift5 is merged to `master`)

**Comment by Binlogo** [comment]
I translated and maintained a separate repo in Chinese [here](https://github.com/Binlogo/Design-Patterns-In-Swift-CN).  Welcome suggestions

[这里](https://github.com/Binlogo/Design-Patterns-In-Swift-CN)整理维护了一个中文版，欢迎查看。

**Comment by ochococo** [comment]
@Binlogo Wow! This is amazing! 👏  Maybe we can somehow merge this repo into the root one? Any ideas how we can do that?

**Comment by ochococo** [comment]
@Binlogo Wdyt? https://github.com/ochococo/Design-Patterns-In-Swift/pull/93

**Comment by Binlogo** [comment]
@ochococo Cool~ Let's do it.
