### ISSUE TITLE
Add a table of contents for convenience.

### ISSUE THREAD

**Issue by Binlogo** [ochococo/Design-Patterns-In-Swift#91]
For the generated giant readme, it's kind of hard to locate a certain pattern. If there is a table of contents like this:

## Table of Contents

| [Behavioral](#behavioral)                              | [Creational](#creational)                | [Structural](#structural)                |
| ------------------------------------------------------ | ---------------------------------------- | ---------------------------------------- |
| [🐝 Chain Of Responsibility](#-chain-of-responsibility) | [🌰 Abstract Factory](#-abstract-factory) | [🔌 Adapter](#-adapter)                   |
| [👫 Command](#-command)                                 | [👷 Builder](#-builder)                   | [🌉 Bridge](#-bridge)                     |
| [🎶 Interpreter](#-interpreter)                         | [🏭 Factory Method](#-factory-method)     | [🌿 Composite](#-composite)               |
| [🍫 Iterator](#-iterator)                               | [🃏 Prototype](#-prototype)               | [🍧 Decorator](#-decorator)               |
| [💐 Mediator](#-mediator)                               | [💍 Singleton](#-singleton)               | [🎁 Façade](#-fa-ade)                     |
| [💾 Memento](#-memento)                                 |                                          | [🍃 Flyweight](#-flyweight)               |
| [👓 Observer](#-observer)                               |                                          | [☔ Protection Proxy](#-protection-proxy) |
| [🐉 State](#-state)                                     |                                          | [🍬 Virtual Proxy](#-virtual-proxy)       |
| [💡 Strategy](#-strategy)                               |                                          |                                          |
| [🏃 Visitor](#-visitor)                                 |                                          |                                          |

it could be very helpful. 😜

**Comment by ochococo** [comment]
Most definitely @Binlogo ❤️
